#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          motorB,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Sensor, S1, touchSensor, sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MOTOR2POS example file for ROBOTC Version 4.0

Demonstrates how to move a NXT LEGO motor to a specific position using a simple
check on the motor encoder position. When running the program, it shows the motor
might overshoot its desired position.

Connections/configuration:
- Connect NXT motor to port B
- Place motor in middle position

Written by R.A. de Callafon, Dept. of MAE
Developed for the UCSD COSMOS Cluster 2 on Engineering Design and Control of Kinetic Sculptures.
More info: https://sites.google.com/eng.ucsd.edu/cosmoscluster2

Latest version: 1.2, July 2022 for RobotC Version 4.x

*/

int touch;
int encoder;

task main()
{
	// definition of integer value that keeps track of the desired position of the motor
	int targetPosition = 0;
	//int currentPosition = nMotorEncoder[motorB];

	// Write some text to the screen
	nxtDisplayTextLine(0, "* MOTOR2POS *");
	nxtDisplayTextLine(1, "NXT motor on B");

	motor[motorB] = 50;
	while (true) {
		touch = SensorValue(touchSensor);
		if (touch > 0) { // Is touching
			motor[motorB] = 0;
			break;
		}
		encoder = nMotorEncoder[motorB];
	}

	nMotorEncoder[motorB] = 0;
	bFloatDuringInactiveMotorPWM = false;

	targetPosition = -350; //encoder position
	nxtDisplayTextLine(2, "Desired = %d", targetPosition);



	while (nMotorEncoder[motorB] > targetPosition) {
		motor[motorB] = -100;
		encoder = nMotorEncoder[motorB];
		//currentPosition = nMotorEncoder[motorB];
	}
	motor[motorB] = 0;

	wait1Msec(1000);
	nxtDisplayTextLine(3, "Final = %d", nMotorEncoder[motorB]);
}

// 50 encoder ticks = 1 inch
