#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,     MotorB,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MOTOR2SONAR example file for ROBOTC Version 4.0

Demonstrates how to move a NXT LEGO motor back and forth via a sonar sensor.

Connections/configuration:
- Connect NXT sonar sensor to port 2
- Connect NXT motor to port B
- Place motor/guide so that sonar sensor is more than 10cm away from obstacle

Written by R.A. de Callafon, Dept. of MAE
Developed for the UCSD COSMOS Cluster 2 on Engineering Design and Control of Kinetic Sculptures.
More info: https://sites.google.com/eng.ucsd.edu/cosmoscluster2

Latest version: 1.2, July 2022 for RobotC Version 4.x

*/
int distance_in_cm = 50;
int sensor;

task main()
{
	// Write some text to the screen
	nxtDisplayTextLine(0, "* MOTOR2SONAR *");
	/* nxtDisplayTextLine(1, "NXT motor on B");
	nxtDisplayTextLine(2, "sonarSensor on S2");*/

	while (true)
	{
		int diddy = SensorValue(sonarSensor);
		sensor = diddy;
		string quandale;

		sprintf(quandale, "%d", diddy);
		while(diddy > distance_in_cm)  //While the Sonar Sensor readings are less than the specified, 'distance_in_cm'
		{
			motor[motorB] = -30;
			diddy = SensorValue(sonarSensor);
			sensor = diddy;// Motor B backward at 30 power level.
		}
		nxtDisplayTextLine(3, "Close to wall!");
		nxtDisplayTextLine(1, quandale); // Otherwise (the sonar sensor readings than the specified, 'distance_in_cm')
		motor[motorB] = 30;                               // Motor B forward at 30 power level.
		wait1Msec(1000);                                  // The program waits 1000 milliseconds before running further code.
		nxtDisplayClearTextLine(3);                       // Clears line 3.
		motor[motorB] = 0;                                // Motor B at 0 power level (stop)
		wait1Msec(1000);                                  // The program waits 1000 milliseconds before running further code.
		nxtDisplayTextLine(3, "Current Distance: " );
	}
}
