#pragma config(Sensor, S1, lightSensor, sensorLightActive)
#pragma config(Motor,  motorB,     MotorB,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MOTOR2LIGHT example file

Demonstrates how to move a NXT LEGO motor back and forth via a light sensor.

Connections/configuration:
- Connect NXT light sensor to port 1
- Connect NXT motor to port B
- Place motor in middle position

Written by R.A. de Callafon, Dept. of MAE
Developed for the UCSD COSMOS Cluster 2 on Engineering Design and Control of Kinetic Sculptures.
More info: https://sites.google.com/eng.ucsd.edu/cosmoscluster2

Latest version: 1.2, July 2022 for RobotC Version 4.x

*/

int light_val = 50;
int sensor;


task main()
{
	// Write some text to the screen
	nxtDisplayTextLine(0, "* MOTOR2LIGHT *");
	nxtDisplayTextLine(1, "NXT motor on B");
	nxtDisplayTextLine(2, "LightSensor on S1");

	// Set the initial threshold value for the light sensor here
	// This should be the reading from the light sensor when NO marble is in front of it


	while (true)
	{
		int diddy = SensorValue(lightSensor);
		sensor = diddy;
		while (SensorValue(lightSensor) < light_val)  // Constantly check if data from lightSensor is below threshold
		{
			motor[motorB] = 30;
			diddy = SensorValue(lightSensor);
			sensor = diddy; // Move Motor B forward with 30%
		}
		nxtDisplayTextLine(3, "See you!");     // Write message
		motor[motorB] = -30;                   // Motor B backward at 30 power level.
		wait1Msec(1000);                       // The program waits 1000 milliseconds before running further code.
		nxtDisplayClearTextLine(3);            // Clears line 3.
		motor[motorB] = 0;                     // Motor B at 0 power level (stop)
		wait1Msec(1000);                       // The program waits 1000 milliseconds before running further code.
	}
}
