#pragma config(Sensor, S2,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,     MotorB,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MOTOR2SONAR example file for ROBOTC Version 4.0

Demonstrates how to move a NXT LEGO motor back and forth via a sonar sensor.

Connections/configuration:
- Connect NXT sonar sensor to port 2
- Connect NXT motor to port B
- Place motor/guide so that sonar sensor is more than 10cm away from obstacle

Written by R.A. de Callafon, Dept. of MAE
Developed for the UCSD COSMOS Cluster 2 on Engineering Design and Control of Kinetic Sculptures.
More info: https://sites.google.com/eng.ucsd.edu/cosmoscluster2

Latest version: 1.2, July 2022 for RobotC Version 4.x

*/
int distance;
bool isRunning;

task main()
{
	int distance_in_cm = 15;   // Create variable 'distance_in_cm' and initialize it to 8(cm).
	isRunning = false;

	// Write some text to the screen
	nxtDisplayTextLine(0, "* MOTOR2SONAR *");
	nxtDisplayTextLine(1, "NXT motor on B");
	nxtDisplayTextLine(2, "sonarSensor on S2");

	motor[motorB] = -30;
	while (true) {
		distance = SensorValue(sonarSensor);
		motor[motorB] = -0.075 * (distance * distance);
		if (distance < 5) { // Is touching
			motor[motorB] = 0;
			break;
		}

	}
	distance = 5;

	while (true)
	{
		isRunning = true;
		while(SensorValue(sonarSensor) < distance_in_cm)  //While the Sonar Sensor readings are less than the specified, 'distance_in_cm'
		{
			distance = SensorValue(sonarSensor);
			motor[motorB] = 30;                            // Motor B backward at 30 power level.
		}
		motor[motorB] = 0;
		break;
	}
}
