#pragma config(Sensor, S1,     diddy,          sensorTouch)
#pragma config(Sensor, S2,     mateo,          sensorLightActive)
#pragma config(Sensor, S3,     mateoGetsDiddled, sensorSONAR)
#pragma config(Motor,  motorB,          MotorB,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MOVEMOTOR example file

Demonstrates how to move a NEXT LEGO motor back and forth.
Connections/configuration:
- Connect NXT motor to port B
- Place motor in middle position

Written by R.A. de Callafon, Dept. of MAE
Developed for the UCSD COSMOS Cluster 2 on Engineering Design and Control of Kinetic Sculptures.
More info: https://sites.google.com/eng.ucsd.edu/cosmoscluster2

Latest version: 1.2, July 2022 for RobotC Version 4.x

*/

task main()
{





































	// Write some text to the screen
	/*nxtDisplayTextLine(0, "* MOVEMOTOR *");
	nxtDisplayTextLine(1, "NXT motor on B");

	*/
	// Task 1
	/* motor[MotorB] = -50;
	wait1Msec(270);
	*/

	// Task 2
	/* for (int i = 0; i < 5; i++) {
		motor[MotorB] = -50;
		wait1Msec(270);

		motor[MotorB] = 0;
		wait1Msec(1000);

		motor[MotorB] = 50;
		wait1Msec(270);

		motor[MotorB] = 0;
		wait1Msec(1000);
	} */

	// Task 3
	/* int x = 0;

	for (int i = 0; i < 5; i++) {
		while (x < 50) {
			motor[MotorB] = x;
			wait1Msec(8);
			x++;
		}
		while (x > 0) {
			motor[MotorB] = x;
			wait1Msec(8);
			x--;
		}
		x = 0;

		motor[MotorB] = 0;
		wait1Msec(100);

		while (x < 50) {
			motor[MotorB] = x;
			wait1Msec(8);
			x++;
		}
		while (x > 0) {
			motor[MotorB] = x;
			wait1Msec(8);
			x--;
		}

		x = 0;

		motor[MotorB] = 0;
		wait1Msec(100);
	}
	*/







	/* while (true)
	{
		nxtDisplayTextLine(2, "0.5s at +30\%");
		motor[motorB] = 30;      // Motor B forward at 30 power level.
		wait1Msec(500);          // The program waits 500 milliseconds before running further code.
		nxtDisplayTextLine(2, "1.0s at -30\%");
		motor[motorB] = -30;     // Motor B backward at 30 power level.
		wait1Msec(1000);         // The program waits 2000 milliseconds before running further code.
		nxtDisplayTextLine(2, "0.5s at 30\%");
		motor[motorB] = 30;      // Motor B forward at 30 power level.
		wait1Msec(500);         // The program waits 1000 milliseconds before running further code.
		motor[motorB] = 0;       // Motor B is run at a 0 power level (stop)
		nxtDisplayTextLine(2, "Stop for 1s");
		wait1Msec(1000);         // The program waits 1000 milliseconds before running further code.
	}
	*/
}
